### ISSUE TITLE
Metrics option 

### ISSUE THREAD

**Issue by omidasadpour** [cartesi/helm-charts#21]
Add option to enable metrics. 

Should support both `grafana agent` and `service monitor`.

**Comment by endersonmaia** [comment]
The way to expose metrics to `grafana-agent` is by annotating the Pod or Service with these annotations:

```
    "prometheus.io/scrape": "true"
    "prometheus.io/path": "/metrics"
    "prometheus.io/port": "8081"
```

We provide a way to annotate the Pods via `.Values.<POD>.podAnnotation` 

I don't think we should add an option to do this kind of thing via `.Values`, with something like `.Values.<POD>.metrics.enabled`, for ex.
