### ISSUE TITLE
match rollups node release and helm release

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/helm-charts#25]
To simplify our helm-chart versioning, I propose using only the chart version and stop using appVersion.

So the chart version should match the cartesi-node version.

For ex.:

cartesi-node:v0.9.1 -> rollups-validatror-node:v0.9.1

**Bugs**

In case we need to make some bug fix to the helm template, we could adopt a `-$NUMBER` suffix like `rollups-validatror-node:v0.9.1-1`.

**Features**

Also, if we have new template functionalities available via `values.yaml` on newer versions, it won't need to be backported.

In case the user wants to use the new feature, they will have to use the newer version.

**Kubernetes compatibility**

We may need to maintain a compatibility matrix for kubernetes versions in case we start using some resource that it's not available on the [currently maintained kubernetes versions](https://kubernetes.io/releases/).

**Comment by endersonmaia** [comment]
I'd like feedback from you @tuler and @oap75.

**Comment by oap75** [comment]
What if the `rollups-validatror-node` version didn't change and we want to update our helm or fix a bug ? 

The question is: How can we handle such scenarios ?

**Comment by endersonmaia** [comment]
> What if the `rollups-validatror-node` version didn't change and we want to update our helm or fix a bug ?
> 
> The question is: How can we handle such scenarios ?

I answer here:

> In case we need to make some bug fix to the helm template, we could adopt a `-$NUMBER` suffix like `rollups-validatror-node:v0.9.1-1.`

The idea is that we won't backport features, just bugfixing.
