### ISSUE TITLE
Use sunodo/devnet container image

### ISSUE THREAD

**Issue by endersonmaia** [cartesi/helm-charts#57]
## 📚 Context

To deploy a localnode, we're using `sunodo/anvil` and copying the state from `sunodo/rollups-node` at an `initContainer`.

After the release of `sunodo/devnet` container image, we can use it without the need to copy the anvil state from another image.

## ✔️ Solution

Use sunodo/devnet directly for the helm-chart localnode.

## Subtasks

- [ ] Use `sunodo/devnet`;
- [ ] Migrate from `cartesi/rollups-cli` to `cast` to make deployments when needed;

**Comment by omidasadpour** [comment]
We have removed the localnode option from helm chart. That's why we do not need to work on this issue anymore !
